// Generated by scripts/gen-deployments.mjs from @meddleware/access-gate-sui@0.0.6 — do not edit.
// Regenerate with `npm run gen:deployments` after bumping that package.

/** One network's `access_gate` deployment. */
export interface AccessGateDeployment {
  /** Package id the types and events are defined at (never changes across upgrades). */
  originalId: string
  /** Latest package version: the call target for transactions. */
  publishedAt: string
  /** The shared `PlatformConfig` object. */
  platformConfigId: string
}

/** Every recorded `access_gate` deployment, by network. */
export const ACCESS_GATE_DEPLOYMENTS = {
  testnet: {
    originalId: '0xd7ddaa94b74330979b2b618fc81206d160a264f1c9ca148a77fa2144301388c9',
    publishedAt: '0xd7ddaa94b74330979b2b618fc81206d160a264f1c9ca148a77fa2144301388c9',
    platformConfigId: '0x3f81489df58233d96798f34ad44de325e1b4df7e4d615affe72ca181969ee7b5',
  },
} as const satisfies Record<string, AccessGateDeployment>

export type AccessGateNetwork = keyof typeof ACCESS_GATE_DEPLOYMENTS

/**
 * The `access_gate` deployment on `network`.
 *
 * @throws {Error} if there is no deployment recorded for `network`.
 */
export function accessGateDeployment(network: string): AccessGateDeployment {
  const deployment = Object.hasOwn(ACCESS_GATE_DEPLOYMENTS, network) ? (ACCESS_GATE_DEPLOYMENTS as Record<string, AccessGateDeployment>)[network] : undefined
  if (!deployment) throw new Error(`no access_gate deployment recorded for ${network}`)
  return deployment
}
