// Generated by scripts/gen-deployments.mjs from @meddleware/access-gate-sui@0.0.5 — do not edit.
// Regenerate with `npm run gen:deployments` after bumping that package.

/** One network's `access_gate` deployment. */
export interface AccessGateDeployment {
  /** Package id the types and events are defined at (never changes across upgrades). */
  originalId: string
  /** Latest package version: the call target for transactions. */
  publishedAt: string
  /** The shared `PlatformConfig` object. */
  platformConfigId: string
}

/** Every recorded `access_gate` deployment, by network. */
export const ACCESS_GATE_DEPLOYMENTS = {
  testnet: {
    originalId: '0xa55789d77b8ae41e604c1c2e9ad9f7b034ca69b028ad0f1eee7d7cc8ad886d41',
    publishedAt: '0xa55789d77b8ae41e604c1c2e9ad9f7b034ca69b028ad0f1eee7d7cc8ad886d41',
    platformConfigId: '0x53a325dc1ebd083c80fd5bed77e3e7cc989285283f188835793af3a7bd8504fa',
  },
} as const satisfies Record<string, AccessGateDeployment>

export type AccessGateNetwork = keyof typeof ACCESS_GATE_DEPLOYMENTS

/**
 * The `access_gate` deployment on `network`.
 *
 * @throws {Error} if there is no deployment recorded for `network`.
 */
export function accessGateDeployment(network: string): AccessGateDeployment {
  const deployment = Object.hasOwn(ACCESS_GATE_DEPLOYMENTS, network) ? (ACCESS_GATE_DEPLOYMENTS as Record<string, AccessGateDeployment>)[network] : undefined
  if (!deployment) throw new Error(`no access_gate deployment recorded for ${network}`)
  return deployment
}
