// Generated by scripts/gen-deployments.mjs from @meddleware/access-gate-sui@0.0.3 — do not edit.
// Regenerate with `npm run gen:deployments` after bumping that package.

/** One network's `access_gate` deployment. */
export interface AccessGateDeployment {
  /** Package id the types and events are defined at (never changes across upgrades). */
  originalId: string
  /** Latest package version: the call target for transactions. */
  publishedAt: string
  /** The shared `PlatformConfig` object. */
  platformConfigId: string
}

/** Every recorded `access_gate` deployment, by network. */
export const ACCESS_GATE_DEPLOYMENTS = {
  testnet: {
    originalId: '0x1a81ca177db039585e575beeeee4759466e55910e936a6733e38dbb65025eea4',
    publishedAt: '0x1a81ca177db039585e575beeeee4759466e55910e936a6733e38dbb65025eea4',
    platformConfigId: '0xe3b949cabe9a0574c03dfc924fb3f96e6f959f2bb86d053ed6229a241c3a23f7',
  },
} as const satisfies Record<string, AccessGateDeployment>

export type AccessGateNetwork = keyof typeof ACCESS_GATE_DEPLOYMENTS

/**
 * The `access_gate` deployment on `network`.
 *
 * @throws {Error} if there is no deployment recorded for `network`.
 */
export function accessGateDeployment(network: string): AccessGateDeployment {
  const deployment = (ACCESS_GATE_DEPLOYMENTS as Record<string, AccessGateDeployment>)[network]
  if (!deployment) throw new Error(`no access_gate deployment recorded for ${network}`)
  return deployment
}
